server:
  port: 8185

spring:
  application:
    name: my-manus
  ai:
    mcp:
      client:
        request-timeout: 60000
        stdio:
          servers-configuration: classpath:/mcp-servers-config.json

manus:
  browser:
    headless: false
