server:
  port: 8225

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: my-manus
  banner:
    location: banner.txt
  profiles:
    active: private
  config:
    import: optional:classpath:application-private.yml,optional:classpath:application-private.properties
  ai:
    mcp:
      client:
        request-timeout: 60000
        stdio:
          servers-configuration: classpath:/mcp-servers-config.json

manus:
  browser:
    headless: false
